baseurl = "http://www.gumoco.nl/"
languageCode = "en-US"
title = "Gumoco - Bram van Dartel - IT Consultancy"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "bram.jpg"
  author = "Bram van Dartel"
  description = "Gumoco - IT Consultancy"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "xirixiz"
  Email         = "root@rootrulez.com"
  Twitter       = "xirixiz"
  LinkedIn      = "bram-van-dartel-a341115"
  Stackoverflow = "xirixiz"

## Main Menu
#[[menu.main]]
#  name = "projects"
#  identifier = "projects"
#  weight = 200
#  url = "/projects/"
